version: '3.7' # specify docker-compose version

services: # define the services
  backendapi: # define the backendapi service
    build: # build the image
      context: ./simple-api/
      dockerfile: ./Dockerfile
    environment: # set environment variables
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
    container_name: backendapi
    ports: # expose ports
      - "8080:8080"
    networks: # network definition
      - app-network
    depends_on: # dependency on other services
      - database

  database:
    build:
      context: ./database/
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    networks:
      - app-network

  httpd:
    build:
      context: ./httpd/
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - backendapi

networks:
  app-network:
    driver: bridge
