version: '3.7'

services:
  backendapi:
    build:
      context: ./simple-api/
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
    container_name: backendapi
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./database/
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    networks:
      - app-network

  httpd:
    build:
      context: ./httpd/
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - backendapi

networks:
  app-network:
    driver: bridge
