---
# tasks file for roles/launch_app
- name: launch app
  docker_container:
    image: bhamitouche/tp-devops-backend
    name: backendapi
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
    ports:
      - 8080:8080
  vars:
    ansible_python_interpreter: /usr/bin/python3